# Generated by Django 4.0 on 2022-11-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_user_admin_user_alternate_mobile_user_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='e_cash_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm_token_android',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm_token_ios',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm_token_web',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='razorpay_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='razorpay_plan_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='razorpay_subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='razorpay_subscription_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='source',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_delivery_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_owner',
        ),
    ]
